# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

extends:
  - "@commitlint/config-conventional"

rules:
  body-max-line-length: [2, "always", 200]
